repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        types: [ json ]
        args: [ --autofix, --no-sort-keys, --indent=4 ]
      - id: check-toml
      - id: check-yaml
        exclude: 'template.*\.yaml$'

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
