repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        types: [ json ]
        args: [ --autofix, --no-sort-keys, --indent=4 ]
      - id: check-toml
      - id: check-yaml
        exclude: 'template.*\.yaml$'

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8.git
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line==1.0.0
          - flake8-builtins==2.1.0
          - flake8-bugbear==22.3.23
          - flake8-comprehensions==3.14.0
          - flake8-eradicate==1.5.0
          - flake8-pep3101==1.3.0
          - flake8-print==4.0.0
          - flake8-logging-format==0.9.0
